language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
  - "pip install ."
  - "pip install coverage"
  - "pip install coveralls"

# command to run tests
script:
  - "coverage run --source=scholarmetrics setup.py test"

notifications:
  email: false
