[build-system]
requires = ["setuptools>=61.2", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "scholarmetrics"
authors = [{name = "Michael E. Rose", email = "Michael.Ernst.Rose@gmail.com"}]
maintainers = [{name = "Michael E. Rose", email = "Michael.Ernst.Rose@gmail.com"}]
description = "Compute scholarly metrics in Python with Pandas and NumPy Edit"
readme = "README.rst"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
keywords = ["metrics", "researchers", "scientists", "academics"]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/Michael-E-Rose/scholarmetrics"
"Bug Tracker" = "https://github.com/Michael-E-Rose/scholarmetrics/issues"
"Documentation (stable)" = "https://scholarmetrics.readthedocs.io/en/stable/"
"Documentation (latest)" = "https://scholarmetrics.readthedocs.io/en/latest/"

[tool.distutils.bdist_wheel]
universal = 1

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["scholarmetrics", "scholarmetrics.*"]

[tool.setuptools_scm]

